(()=>{
'use strict';
const memories=[{text:"you showed up and the noise went quiet"},{text:"some people feel like home before you even arrive"},{text:"I keep replaying the small things — they were never small"},{text:"you laugh and the whole room rearranges itself around you"},{text:"there's a version of me that only exists when you're around"},{text:"not every silence needs filling — ours never did"},{text:"you turned a regular Tuesday into something I'll remember forever"},{text:"two cities, one thread pulling us closer"},{text:"I think the universe was just waiting for us to meet"},{text:"you're the 2am thought that stays till morning"},{text:"some flowers only bloom when the right person walks by"},{text:"I didn't plan any of this — and that's the best part"},{text:"you're not a chapter, Sathi — you're the whole story"},{text:"this one's just because... you exist"}];
const flowers=[];let flowerCount=0,memoryIndex=0,toastTimeout=null,finalShown=false;
const el=id=>document.getElementById(id);
const introOverlay=el('introOverlay'),startBtn=el('startBtn'),scene=el('scene');
const flowerCanvas=el('flowerCanvas'),ambientCanvas=el('ambientCanvas'),introStarsCanvas=el('introStars');
const hint=el('hint'),counter=el('flowerCounter'),countEl=el('count'),counterLabel=el('counterLabel');
const memoryToast=el('memoryToast'),memoryText=el('memoryText'),vaseContainer=el('vaseContainer'),finalReveal=el('finalReveal');
const fCtx=flowerCanvas.getContext('2d'),aCtx=ambientCanvas.getContext('2d'),iCtx=introStarsCanvas.getContext('2d');
function hexRgb(h){return{r:parseInt(h.slice(1,3),16),g:parseInt(h.slice(3,5),16),b:parseInt(h.slice(5,7),16)};}
function rgba(h,a){const c=hexRgb(h);return'rgba('+c.r+','+c.g+','+c.b+','+a+')';}
function rand(a,b){return Math.random()*(b-a)+a;}
function easeOut(t){return 1-Math.pow(1-t,3);}
function bezPt(p0,p1,p2,p3,t){const m=1-t;return m*m*m*p0+3*m*m*t*p1+3*m*t*t*p2+t*t*t*p3;}
function resize(){const d=devicePixelRatio||1;[flowerCanvas,ambientCanvas].forEach(c=>{c.width=innerWidth*d;c.height=innerHeight*d;c.getContext('2d').setTransform(d,0,0,d,0,0);});introStarsCanvas.width=innerWidth*d;introStarsCanvas.height=innerHeight*d;iCtx.setTransform(d,0,0,d,0,0);}
addEventListener('resize',resize);resize();
const stars=Array.from({length:80},()=>({x:rand(0,innerWidth),y:rand(0,innerHeight),r:rand(0.3,1.8),a:Math.random(),s:rand(0.003,0.013)}));
function drawIntroStars(){iCtx.clearRect(0,0,innerWidth,innerHeight);for(const s of stars){s.a+=s.s*(Math.random()>0.5?1:-1);s.a=Math.max(0.1,Math.min(0.9,s.a));iCtx.beginPath();iCtx.arc(s.x,s.y,s.r,0,Math.PI*2);iCtx.fillStyle='rgba(255,250,230,'+s.a+')';iCtx.fill();}}
function getVaseTop(){return vaseContainer.getBoundingClientRect().top;}
function startExperience(){introOverlay.classList.add('hidden');scene.classList.add('active');}
startBtn.addEventListener('click',startExperience);
startBtn.addEventListener('touchend',function(e){e.preventDefault();startExperience();});
const flies=Array.from({length:30},()=>({x:rand(0,innerWidth),y:rand(0,innerHeight),r:rand(0.5,2.5),sp:rand(0.1,0.3),ang:rand(0,Math.PI*2),dr:rand(0.002,0.007),a:Math.random(),ad:(Math.random()>0.5?1:-1)*rand(0.003,0.011)}));
function drawFireflies(){aCtx.clearRect(0,0,innerWidth,innerHeight);for(const f of flies){f.ang+=f.dr;f.x+=Math.cos(f.ang)*f.sp;f.y+=Math.sin(f.ang)*f.sp*0.6;f.a+=f.ad;if(f.a>0.8||f.a<0.05)f.ad*=-1;f.a=Math.max(0,Math.min(1,f.a));if(f.x<-10)f.x=innerWidth+10;if(f.x>innerWidth+10)f.x=-10;if(f.y<-10)f.y=innerHeight+10;if(f.y>innerHeight+10)f.y=-10;aCtx.beginPath();aCtx.arc(f.x,f.y,f.r,0,Math.PI*2);aCtx.fillStyle='rgba(255,230,180,'+f.a*0.6+')';aCtx.fill();aCtx.beginPath();aCtx.arc(f.x,f.y,f.r*5,0,Math.PI*2);aCtx.fillStyle='rgba(255,230,180,'+f.a*0.06+')';aCtx.fill();}}
const TYPES=[{name:'rose',base:'#e05580',light:'#f4a0b8',dark:'#a03050',center:'#d04070'},{name:'rose',base:'#c94070',light:'#e88ca5',dark:'#901840',center:'#b03060'},{name:'sunflower',base:'#f5c040',light:'#ffe080',dark:'#d09820',center:'#6b4410'},{name:'lily',base:'#f0f0f0',light:'#ffffff',dark:'#d0d0d0',center:'#90c040'},{name:'lily',base:'#f4a7bb',light:'#fcd0dd',dark:'#d07090',center:'#80b040'},{name:'tulip',base:'#e04060',light:'#f08090',dark:'#b02040',center:'#c8e040'},{name:'tulip',base:'#9060c0',light:'#b890e0',dark:'#6030a0',center:'#c8e040'},{name:'tulip',base:'#ff8a65',light:'#ffb89a',dark:'#d05030',center:'#c8e040'},{name:'cherry',base:'#f8c0d0',light:'#ffe0ea',dark:'#e090a8',center:'#f0d060'},{name:'cherry',base:'#ffffff',light:'#ffffff',dark:'#f0d0d8',center:'#f0d060'}];
class Flower{
constructor(x,baseY){const t=TYPES[Math.floor(rand(0,TYPES.length))];this.x=x;this.baseY=baseY;this.typeName=t.name;this.base=t.base;this.light=t.light;this.dark=t.dark;this.center=t.center;this.stemH=rand(80,130)+innerHeight*0.07;this.sz=rand(13,20);this.rot=rand(0,Math.PI*2);this.swayOff=rand(0,Math.PI*2);this.swayAmt=rand(2,5);this.curve=rand(-25,25);this.grow=0;this.bloom=0;this.leaves=Array.from({length:Math.floor(rand(1,3))},()=>({t:rand(0.2,0.6),side:Math.random()>0.5?1:-1,size:rand(10,16),angle:rand(0.2,0.55)}));}
update(){if(this.grow<1)this.grow=Math.min(1,this.grow+0.012);else if(this.bloom<1)this.bloom=Math.min(1,this.bloom+0.009);}
draw(ctx,time){const sway=Math.sin(time*0.0007+this.swayOff)*this.swayAmt,h=this.stemH*easeOut(this.grow),cx=this.x+this.curve*this.grow,tx=this.x+sway,ty=this.baseY-h;ctx.save();ctx.beginPath();ctx.moveTo(this.x,this.baseY);ctx.bezierCurveTo(this.x,this.baseY-h*0.35,cx+sway*0.3,this.baseY-h*0.65,tx,ty);const sg=ctx.createLinearGradient(this.x,this.baseY,tx,ty);sg.addColorStop(0,'rgba(55,95,45,'+0.85*this.grow+')');sg.addColorStop(1,'rgba(75,130,60,'+0.75*this.grow+')');ctx.strokeStyle=sg;ctx.lineWidth=2.5;ctx.lineCap='round';ctx.stroke();ctx.restore();if(this.grow>0.25){const la=Math.min(1,(this.grow-0.25)/0.35);for(const lf of this.leaves){const lx=bezPt(this.x,this.x,cx+sway*0.3,tx,lf.t),ly=bezPt(this.baseY,this.baseY-h*0.35,this.baseY-h*0.65,ty,lf.t);ctx.save();ctx.translate(lx,ly);ctx.rotate(lf.side*lf.angle+sway*0.01);const s=lf.size*la,d=lf.side;ctx.beginPath();ctx.moveTo(0,0);ctx.bezierCurveTo(d*s*0.3,-s*0.22,d*s*0.8,-s*0.12,d*s,0);ctx.bezierCurveTo(d*s*0.8,s*0.12,d*s*0.3,s*0.18,0,0);const lg=ctx.createLinearGradient(0,0,d*s,0);lg.addColorStop(0,'rgba(65,125,50,'+0.7*la+')');lg.addColorStop(0.5,'rgba(85,155,65,'+0.6*la+')');lg.addColorStop(1,'rgba(55,105,40,'+0.5*la+')');ctx.fillStyle=lg;ctx.fill();ctx.restore();}}if(this.bloom>0){const bp=Math.min(1,this.bloom*1.05);ctx.save();ctx.translate(tx,ty);ctx.rotate(this.rot+sway*0.005);const gr=this.sz*3.5*bp,grd=ctx.createRadialGradient(0,0,0,0,0,gr);grd.addColorStop(0,rgba(this.base,0.12*bp));grd.addColorStop(1,rgba(this.base,0));ctx.fillStyle=grd;ctx.fillRect(-gr,-gr,gr*2,gr*2);switch(this.typeName){case'rose':this.drawRose(ctx,bp,time);break;case'sunflower':this.drawSunflower(ctx,bp,time);break;case'lily':this.drawLily(ctx,bp,time);break;case'tulip':this.drawTulip(ctx,bp,time);break;case'cherry':this.drawCherry(ctx,bp,time);break;}ctx.restore();}}
drawRose(ctx,bp,time){const s=this.sz;for(let layer=3;layer>=1;layer--){const lbp=Math.max(0,Math.min(1,(bp-(3-layer)*0.15)/0.7));if(lbp<=0)continue;const count=layer===3?7:layer===2?5:4,radius=s*(0.3+layer*0.25)*lbp,pH=s*(0.5+layer*0.15)*lbp,pW=s*(0.35+layer*0.08)*lbp;for(let i=0;i<count;i++){const a=(i/count)*Math.PI*2+layer*0.3,w=Math.sin(time*0.0005+i+layer)*0.02;ctx.save();ctx.rotate(a+w);ctx.translate(0,-radius*0.4);ctx.beginPath();ctx.moveTo(0,0);ctx.bezierCurveTo(-pW*0.6,-pH*0.3,-pW*0.5,-pH*0.9,0,-pH);ctx.bezierCurveTo(pW*0.5,-pH*0.9,pW*0.6,-pH*0.3,0,0);const pg=ctx.createLinearGradient(0,0,0,-pH);pg.addColorStop(0,rgba(this.dark,0.7*lbp));pg.addColorStop(0.4,rgba(this.base,0.75*lbp));pg.addColorStop(1,rgba(this.light,0.65*lbp));ctx.fillStyle=pg;ctx.fill();ctx.strokeStyle=rgba(this.light,0.2*lbp);ctx.lineWidth=0.5;ctx.stroke();ctx.restore();}}ctx.beginPath();ctx.arc(0,0,s*0.15*bp,0,Math.PI*2);ctx.fillStyle=rgba(this.dark,0.5*bp);ctx.fill();}
drawSunflower(ctx,bp,time){const s=this.sz,pLen=s*1.2*bp,pW=s*0.22*bp;for(let layer=0;layer<2;layer++){const off=layer*(Math.PI/14),len=pLen*(layer===0?1:0.85),al=layer===0?0.8:0.65;for(let i=0;i<14;i++){const a=(i/14)*Math.PI*2+off,w=Math.sin(time*0.0006+i*0.5)*0.03;ctx.save();ctx.rotate(a+w);ctx.beginPath();ctx.moveTo(0,0);ctx.bezierCurveTo(-pW,-len*0.3,-pW*0.7,-len*0.8,0,-len);ctx.bezierCurveTo(pW*0.7,-len*0.8,pW,-len*0.3,0,0);const pg=ctx.createLinearGradient(0,0,0,-len);pg.addColorStop(0,rgba(this.dark,al*bp));pg.addColorStop(0.5,rgba(this.base,al*bp));pg.addColorStop(1,rgba(this.light,(al-0.1)*bp));ctx.fillStyle=pg;ctx.fill();ctx.restore();}}const cR=s*0.45*bp;ctx.beginPath();ctx.arc(0,0,cR,0,Math.PI*2);const cg=ctx.createRadialGradient(0,0,0,0,0,cR);cg.addColorStop(0,rgba('#3d2008',0.9*bp));cg.addColorStop(0.7,rgba(this.center,0.85*bp));cg.addColorStop(1,rgba(this.dark,0.7*bp));ctx.fillStyle=cg;ctx.fill();const golden=Math.PI*(3-Math.sqrt(5)),seeds=Math.floor(40*bp);for(let i=0;i<seeds;i++){const r=cR*0.85*Math.sqrt(i/seeds),th=i*golden;ctx.beginPath();ctx.arc(Math.cos(th)*r,Math.sin(th)*r,1.2,0,Math.PI*2);ctx.fillStyle='rgba(80,50,10,'+0.5*bp+')';ctx.fill();}}
drawLily(ctx,bp,time){const s=this.sz,count=6,pLen=s*1.3*bp,pW=s*0.35*bp;for(let i=0;i<count;i++){const a=(i/count)*Math.PI*2,w=Math.sin(time*0.0005+i*1.2)*0.025;ctx.save();ctx.rotate(a+w);ctx.beginPath();ctx.moveTo(0,0);ctx.bezierCurveTo(-pW*0.4,-pLen*0.25,-pW*0.8,-pLen*0.6,-pW*0.2,-pLen);ctx.bezierCurveTo(0,-pLen*1.08,0,-pLen*1.08,pW*0.2,-pLen);ctx.bezierCurveTo(pW*0.8,-pLen*0.6,pW*0.4,-pLen*0.25,0,0);const pg=ctx.createLinearGradient(0,0,0,-pLen);pg.addColorStop(0,rgba(this.center,0.4*bp));pg.addColorStop(0.3,rgba(this.base,0.7*bp));pg.addColorStop(1,rgba(this.light,0.6*bp));ctx.fillStyle=pg;ctx.fill();ctx.restore();}for(let i=0;i<5;i++){const a=(i/5)*Math.PI*2+0.3,len=s*0.6*bp,sx=Math.cos(a)*len*0.8,sy=Math.sin(a)*len*0.8;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(sx,sy);ctx.strokeStyle=rgba(this.center,0.5*bp);ctx.lineWidth=1;ctx.stroke();ctx.beginPath();ctx.arc(sx,sy,2*bp,0,Math.PI*2);ctx.fillStyle=rgba('#c08020',0.8*bp);ctx.fill();}}
drawTulip(ctx,bp,time){const s=this.sz,pH=s*1.4*bp,pW=s*0.55*bp;for(let i=0;i<3;i++){const a=(i/3)*Math.PI*2+Math.PI/3,w=Math.sin(time*0.0004+i)*0.02;ctx.save();ctx.rotate(a+w);ctx.beginPath();ctx.moveTo(0,0);ctx.bezierCurveTo(-pW*0.7,-pH*0.15,-pW*0.9,-pH*0.6,-pW*0.15,-pH);ctx.quadraticCurveTo(0,-pH*1.05,pW*0.15,-pH);ctx.bezierCurveTo(pW*0.9,-pH*0.6,pW*0.7,-pH*0.15,0,0);ctx.fillStyle=rgba(this.dark,0.5*bp);ctx.fill();ctx.restore();}for(let i=0;i<3;i++){const a=(i/3)*Math.PI*2,w=Math.sin(time*0.0004+i*2)*0.02;ctx.save();ctx.rotate(a+w);ctx.beginPath();ctx.moveTo(0,0);ctx.bezierCurveTo(-pW*0.65,-pH*0.15,-pW*0.85,-pH*0.55,-pW*0.12,-pH);ctx.quadraticCurveTo(0,-pH*1.06,pW*0.12,-pH);ctx.bezierCurveTo(pW*0.85,-pH*0.55,pW*0.65,-pH*0.15,0,0);const pg=ctx.createLinearGradient(0,0,0,-pH);pg.addColorStop(0,rgba(this.dark,0.75*bp));pg.addColorStop(0.4,rgba(this.base,0.8*bp));pg.addColorStop(0.8,rgba(this.light,0.7*bp));pg.addColorStop(1,rgba(this.light,0.5*bp));ctx.fillStyle=pg;ctx.fill();ctx.restore();}ctx.beginPath();ctx.arc(0,-s*0.15*bp,s*0.08*bp,0,Math.PI*2);ctx.fillStyle=rgba(this.center,0.6*bp);ctx.fill();}
drawCherry(ctx,bp,time){const s=this.sz,count=5,pLen=s*0.95*bp,pW=s*0.45*bp;for(let i=0;i<count;i++){const a=(i/count)*Math.PI*2,w=Math.sin(time*0.0006+i*1.5)*0.03;ctx.save();ctx.rotate(a+w);ctx.beginPath();ctx.moveTo(0,0);ctx.bezierCurveTo(-pW*0.6,-pLen*0.2,-pW*0.9,-pLen*0.7,-pW*0.25,-pLen*0.92);ctx.quadraticCurveTo(0,-pLen*0.78,pW*0.25,-pLen*0.92);ctx.bezierCurveTo(pW*0.9,-pLen*0.7,pW*0.6,-pLen*0.2,0,0);const pg=ctx.createRadialGradient(0,-pLen*0.3,0,0,-pLen*0.3,pLen);pg.addColorStop(0,rgba(this.base,0.75*bp));pg.addColorStop(0.5,rgba(this.light,0.6*bp));pg.addColorStop(1,rgba(this.light,0.35*bp));ctx.fillStyle=pg;ctx.fill();ctx.restore();}for(let i=0;i<8;i++){const a=(i/8)*Math.PI*2,r=s*0.2*bp,ex=Math.cos(a)*r,ey=Math.sin(a)*r;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(ex,ey);ctx.strokeStyle=rgba(this.center,0.4*bp);ctx.lineWidth=0.7;ctx.stroke();ctx.beginPath();ctx.arc(ex,ey,1.5*bp,0,Math.PI*2);ctx.fillStyle=rgba(this.center,0.7*bp);ctx.fill();}}}
const particles=[];
function spawnBurst(x,y,color){for(let i=0;i<14;i++){const a=(i/14)*Math.PI*2+rand(-0.3,0.3),sp=rand(1,2.5);particles.push({x,y,vx:Math.cos(a)*sp,vy:Math.sin(a)*sp-1.5,life:1,decay:rand(0.008,0.018),size:rand(2,5),color});}}
function tickParticles(){for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.x+=p.vx;p.y+=p.vy;p.vy+=0.03;p.vx*=0.99;p.life-=p.decay;if(p.life<=0)particles.splice(i,1);}}
function drawParticles(ctx){for(const p of particles){ctx.globalAlpha=p.life*0.6;ctx.beginPath();ctx.arc(p.x,p.y,p.size*p.life,0,Math.PI*2);ctx.fillStyle=p.color;ctx.fill();}ctx.globalAlpha=1;}
function showMemory(mem){if(toastTimeout)clearTimeout(toastTimeout);memoryToast.classList.remove('show');void memoryToast.offsetWidth;memoryText.textContent=mem.text;memoryToast.classList.add('show');toastTimeout=setTimeout(function(){memoryToast.classList.remove('show');},3500);}
function plant(cx,cy){var rect=flowerCanvas.getBoundingClientRect(),x=cx-rect.left,y=cy-rect.top,vt=getVaseTop();if(y>vt+10)return;var mem=memories[memoryIndex%memories.length];memoryIndex++;flowers.push(new Flower(x,vt));flowerCount++;countEl.textContent=flowerCount;counter.classList.add('visible');counterLabel.textContent=flowerCount===1?'thought bloomed':'thoughts bloomed';showMemory(mem);spawnBurst(x,vt-5,TYPES[Math.floor(rand(0,TYPES.length))].base);if(flowerCount===1){hint.style.transition='opacity 1s ease';hint.style.opacity='0';}if(flowerCount===memories.length&&!finalShown){finalShown=true;setTimeout(function(){finalReveal.classList.add('visible');},4000);}}
flowerCanvas.addEventListener('click',function(e){plant(e.clientX,e.clientY);});
flowerCanvas.addEventListener('touchstart',function(e){e.preventDefault();plant(e.touches[0].clientX,e.touches[0].clientY);},{passive:false});
finalReveal.addEventListener('click',function(){finalReveal.classList.remove('visible');});
var introActive=true;
function animate(t){if(introActive){drawIntroStars();if(introOverlay.classList.contains('hidden'))setTimeout(function(){introActive=false;},1200);}fCtx.clearRect(0,0,innerWidth,innerHeight);var vt=getVaseTop(),gg=fCtx.createLinearGradient(0,vt-20,0,innerHeight);gg.addColorStop(0,'rgba(30,50,30,0)');gg.addColorStop(0.5,'rgba(30,50,30,0.08)');gg.addColorStop(1,'rgba(20,40,20,0.15)');fCtx.fillStyle=gg;fCtx.fillRect(0,0,innerWidth,innerHeight);var vg=fCtx.createRadialGradient(innerWidth/2,vt+30,5,innerWidth/2,vt+30,150);vg.addColorStop(0,'rgba(212,165,116,0.06)');vg.addColorStop(1,'rgba(212,165,116,0)');fCtx.fillStyle=vg;fCtx.fillRect(0,0,innerWidth,innerHeight);for(var i=0;i<flowers.length;i++){flowers[i].update();flowers[i].draw(fCtx,t);}tickParticles();drawParticles(fCtx);drawFireflies();requestAnimationFrame(animate);}
requestAnimationFrame(animate);
})();
